### ISSUE TITLE
Add clean task

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-build-tasks#2]
A `clean` task would intentionally delete all of the files that can be generated with the other tasks.

Optionally, have subtasks that wipe out, for instance, just the language directory, just the `.js` files, just the `.css` and `.map` files, just the optimized images (leaving the raw ones) etc.

Makes it easier to debug when trying to confirm that something is happening or not.

**Comment by craigsimps** [comment]
Clean tasks have now been added, specifically:

* `gulp clean` will run all of the below tasks.
* `gulp clean:css` will delete `.css` files and `.css.map` files from the theme root.
* `gulp clean:js` will delete `.js` and `.min.js` files from our `/js/` output directory.
* `gulp clean:images` will delete all image files from our `/images/` output directory.
* `gulp clean:i18n` will delete our generated .pot file within `/languages/`.
* `gulp clean:bower` will delete any files compiled from Bower components (CSS & JS).
* `gulp clean:bowerjs` will delete any JS files compiled from Bower components, usually `vendor.js` and `vendor.min.js`.
* `gulp clean:bowercss` will delete any CSS files compiled from Bower components, usually `vendor.css` and `vendor.min.css`.
