### ISSUE TITLE
Add JSValidate task

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-build-tasks#8]
While JSONLint checks for json syntax validation, wider JS syntax validation can also be checked, both for original `.js`, and concat/minified `.js` files, as well as the build `.js` files in this repo too.

**Comment by craigsimps** [comment]
A JS Validate task is now available against theme files using `gulp lint:jsvalidate` or `gulp-build-tasks` files using `gulp self:jsvalidate`.

Added as part of https://github.com/craigsimps/gulp-build-tasks/commit/b3882bb50d787c468f5e93368b7d50fa6192eb82 and https://github.com/craigsimps/gulp-build-tasks/commit/cc53758b13c6c65b4106e64a21cdbd1ab8f0b2a0
